const objects=[
{name:'The Sun',place:'inside',type:'Stars',icon:'☀',color:'#ffad32',summary:'The star at the center of our Solar System. Its light and heat make life on Earth possible.',facts:['Distance from Earth','149.6 million km','Composition','Hydrogen and helium','Diameter','1.39 million km','Age','About 4.6 billion years']},
{name:'Mercury',place:'inside',type:'Planets',icon:'●',color:'#99938b',summary:'The smallest and closest planet to the Sun, with a cratered surface and extreme temperatures.',facts:['Order from Sun','1st','Type','Terrestrial','Moons','0','Year','88 Earth days']},
{name:'Venus',place:'inside',type:'Planets',icon:'●',color:'#d9a15c',summary:'A rocky world whose runaway greenhouse effect makes it the hottest planet.',facts:['Order from Sun','2nd','Type','Terrestrial','Moons','0','Year','224.7 Earth days']},
{name:'Earth',place:'inside',type:'Planets',icon:'●',color:'#3e89cf',summary:'Our ocean-covered home and the only world currently known to support life.',facts:['Order from Sun','3rd','Type','Terrestrial','Moons','1','Year','365.25 days']},
{name:'Mars',place:'inside',type:'Planets',icon:'●',color:'#d65a35',summary:'A cold, rocky desert with giant volcanoes, deep canyons and evidence of ancient rivers.',facts:['Order from Sun','4th','Type','Terrestrial','Moons','2','Year','687 Earth days']},
{name:'Jupiter',place:'inside',type:'Planets',icon:'●',color:'#d69b69',summary:'The largest planet, famous for colorful cloud bands and the Great Red Spot.',facts:['Order from Sun','5th','Type','Gas giant','Moons','95+','Year','11.86 Earth years']},
{name:'Saturn',place:'inside',type:'Planets',icon:'◉',color:'#d8bd78',summary:'A gas giant surrounded by spectacular rings made mainly of water ice.',facts:['Order from Sun','6th','Type','Gas giant','Moons','140+','Year','29.5 Earth years']},
{name:'Uranus',place:'inside',type:'Planets',icon:'●',color:'#79c8d4',summary:'An ice giant that rotates on its side, probably because of an ancient collision.',facts:['Order from Sun','7th','Type','Ice giant','Moons','28','Year','84 Earth years']},
{name:'Neptune',place:'inside',type:'Planets',icon:'●',color:'#4169cf',summary:'A distant blue ice giant with the fastest planetary winds in the Solar System.',facts:['Order from Sun','8th','Type','Ice giant','Moons','16','Year','164.8 Earth years']},
{name:'The Moon',place:'inside',type:'Moons',parent:'Earth',icon:'●',color:'#aaa9a2',summary:'Earth’s natural satellite influences tides and preserves a record of early impacts.',facts:['Orbits','Earth','Diameter','3,475 km','Surface','Rocky and cratered','Orbit','27.3 days']},
{name:'Phobos',place:'inside',type:'Moons',parent:'Mars',icon:'●',color:'#806f60',summary:'The larger inner moon of Mars is slowly spiraling toward the planet.',facts:['Orbits','Mars','Shape','Irregular','Diameter','22.5 km','Orbit','7.7 hours']},
{name:'Deimos',place:'inside',type:'Moons',parent:'Mars',icon:'●',color:'#9a8873',summary:'Mars’s smaller outer moon is likely made of rock and carbon-rich material.',facts:['Orbits','Mars','Shape','Irregular','Diameter','12.4 km','Orbit','30.3 hours']},
{name:'Io',place:'inside',type:'Moons',parent:'Jupiter',icon:'●',color:'#dbc94e',summary:'The most volcanically active world known, heated by Jupiter’s tidal forces.',facts:['Orbits','Jupiter','Diameter','3,643 km','Surface','Sulfur and lava','Feature','Active volcanoes']},
{name:'Europa',place:'inside',type:'Moons',parent:'Jupiter',icon:'●',color:'#b9a77c',summary:'An icy moon that may hide a vast saltwater ocean beneath its surface.',facts:['Orbits','Jupiter','Diameter','3,122 km','Surface','Water ice','Feature','Subsurface ocean']},
{name:'Ganymede',place:'inside',type:'Moons',parent:'Jupiter',icon:'●',color:'#8b7765',summary:'The largest moon and the only one known to have its own magnetic field.',facts:['Orbits','Jupiter','Diameter','5,268 km','Surface','Ice and rock','Feature','Largest moon']},
{name:'Callisto',place:'inside',type:'Moons',parent:'Jupiter',icon:'●',color:'#756d66',summary:'An ancient, heavily cratered moon that may contain a deep ocean.',facts:['Orbits','Jupiter','Diameter','4,821 km','Surface','Ice and rock','Feature','Many craters']},
{name:'Titan',place:'inside',type:'Moons',parent:'Saturn',icon:'●',color:'#d9a84f',summary:'A moon with a thick atmosphere and lakes and rivers of liquid methane.',facts:['Orbits','Saturn','Diameter','5,150 km','Atmosphere','Mostly nitrogen','Surface','Methane lakes']},
{name:'Enceladus',place:'inside',type:'Moons',parent:'Saturn',icon:'●',color:'#dce9ed',summary:'An icy moon whose south-polar geysers spray material from an underground ocean.',facts:['Orbits','Saturn','Diameter','504 km','Surface','Water ice','Feature','Ocean geysers']},
{name:'Titania',place:'inside',type:'Moons',parent:'Uranus',icon:'●',color:'#9b9189',summary:'The largest moon of Uranus, marked by canyons, faults and craters.',facts:['Orbits','Uranus','Diameter','1,578 km','Composition','Ice and rock','Feature','Fault valleys']},
{name:'Triton',place:'inside',type:'Moons',parent:'Neptune',icon:'●',color:'#b8a7a4',summary:'Neptune’s largest moon orbits backward and may be a captured Kuiper Belt object.',facts:['Orbits','Neptune','Diameter','2,707 km','Surface','Nitrogen ice','Feature','Retrograde orbit']},
{name:'Ceres',place:'inside',type:'Asteroids',icon:'◆',color:'#77756f',summary:'The largest asteroid-belt object and the inner Solar System’s only dwarf planet.',facts:['Location','Main belt','Diameter','940 km','Class','Dwarf planet','Composition','Rock, ice and salts']},
{name:'Vesta',place:'inside',type:'Asteroids',icon:'◆',color:'#a08d79',summary:'A large differentiated asteroid with a giant south-polar impact basin.',facts:['Location','Main belt','Diameter','525 km','Class','V-type','Mission','Dawn']},
{name:'Bennu',place:'inside',type:'Asteroids',icon:'◆',color:'#665e55',summary:'A carbon-rich near-Earth asteroid sampled by NASA’s OSIRIS-REx mission.',facts:['Location','Near-Earth orbit','Diameter','About 500 m','Class','B-type','Mission','OSIRIS-REx']},
{name:'Eros',place:'inside',type:'Asteroids',icon:'◆',color:'#8b715c',summary:'An elongated near-Earth asteroid visited by the NEAR Shoemaker spacecraft.',facts:['Location','Near-Earth orbit','Length','About 34 km','Class','S-type','Mission','NEAR Shoemaker']},
{name:'Proxima Centauri',place:'outside',type:'Stars',icon:'✦',color:'#ef624d',summary:'The closest known star to the Sun. This small red dwarf hosts at least two confirmed planets.',facts:['Distance','4.24 light-years','Type','Red dwarf','Mass','About 12% of the Sun','Constellation','Centaurus']},
{name:'TRAPPIST-1e',place:'outside',type:'Planets',icon:'●',color:'#5e89c9',summary:'An Earth-sized rocky exoplanet orbiting in the temperate region of an ultra-cool red dwarf.',facts:['Distance','40.7 light-years','Composition','Probably rocky','Size','0.92 Earth radii','Length of year','6.1 Earth days']},
{name:'Orion Nebula',place:'outside',type:'Nebulas',icon:'☁',color:'#ae69dd',summary:'A nearby stellar nursery where dense clouds of gas and dust are forming thousands of new stars.',facts:['Distance','About 1,344 light-years','Type','Emission nebula','Width','About 24 light-years','Constellation','Orion']},
{name:'Crab Nebula',place:'outside',type:'Nebulas',icon:'☁',color:'#de637e',summary:'The expanding remains of a massive star whose explosion was observed from Earth in 1054.',facts:['Distance','About 6,500 light-years','Type','Supernova remnant','Width','About 11 light-years','Center','A rapidly spinning pulsar']},
{name:'Andromeda Galaxy',place:'outside',type:'Galaxies',icon:'◎',color:'#779de5',summary:'The nearest large galaxy to the Milky Way and a future merger partner of our home galaxy.',facts:['Distance','2.5 million light-years','Type','Spiral galaxy','Stars','About one trillion','Diameter','About 152,000 light-years']},
{name:'Sombrero Galaxy',place:'outside',type:'Galaxies',icon:'◎',color:'#dfb170',summary:'A striking galaxy viewed nearly edge-on, with a bright center and a dark lane of cosmic dust.',facts:['Distance','About 29 million light-years','Type','Peculiar galaxy','Catalog name','Messier 104','Constellation','Virgo']}
];
let place='all',type='All';const home=document.querySelector('#home'),explorer=document.querySelector('#explorer'),details=document.querySelector('#details'),cards=document.querySelector('#cards'),title=document.querySelector('#sectionTitle');
function openExplorer(nextPlace){
  place=nextPlace;type='All';home.classList.add('hidden');details.classList.add('hidden');explorer.classList.remove('hidden');
  document.querySelectorAll('.type').forEach(button=>{
    const available=button.dataset.type==='All'||place==='all'||objects.some(o=>o.place===place&&o.type===button.dataset.type);
    button.classList.toggle('hidden',!available);button.classList.toggle('active',button.dataset.type==='All');
  });
  render();
}
function render(){const shown=objects.filter(o=>(place==='all'||o.place===place)&&(type==='All'||o.type===type));title.textContent=`${place==='inside'?'Inside the Solar System':place==='outside'?'Outside the Solar System':'All Space'} · ${type}`;cards.innerHTML=shown.map(o=>`<button class="card" data-name="${o.name}"><span class="card-icon" style="--color:${o.color}">${o.icon}</span><h3>${o.name}</h3><small>${o.type}${o.parent?` · Orbits ${o.parent}`:''}</small><p>${o.summary}</p></button>`).join('')||'<p>No objects in this category yet.</p>';cards.querySelectorAll('.card').forEach(c=>c.onclick=()=>show(c.dataset.name))}
function show(name){
  const o=objects.find(x=>x.name===name);const moons=objects.filter(x=>x.parent===o.name);
  const related=moons.length?`<section class="related"><h3>Explore its moons</h3><div class="related-list">${moons.map(m=>`<button onclick="show('${m.name}')">${m.name}</button>`).join('')}</div></section>`:o.parent?`<section class="related"><h3>Parent planet</h3><div class="related-list"><button onclick="show('${o.parent}')">${o.parent}</button></div></section>`:'';
  explorer.classList.add('hidden');details.classList.remove('hidden');details.innerHTML=`<button class="back" onclick="closeDetails()">← Back to list</button><div class="hero-object" style="--color:${o.color}">${o.icon}</div><h2>${o.name}</h2><p>${o.summary}</p><div class="facts">${Array.from({length:o.facts.length/2},(_,i)=>`<div class="fact"><b>${o.facts[i*2]}</b>${o.facts[i*2+1]}</div>`).join('')}</div>${related}`;
}
function closeDetails(){details.classList.add('hidden');explorer.classList.remove('hidden')}
function goHome(){home.classList.remove('hidden');explorer.classList.add('hidden');details.classList.add('hidden')}
document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>openExplorer(b.dataset.place));document.querySelectorAll('.type').forEach(b=>b.onclick=()=>{type=b.dataset.type;document.querySelectorAll('.type').forEach(x=>x.classList.toggle('active',x===b));render()});