window.GUIDE_DATA.push(
{name:'Planet Formation',place:'study',type:'Theory',icon:'◌',color:'#8e79d6',summary:'Dust in a protoplanetary disk accretes into planetesimals and planets.',facts:['Core accretion','Dust → planetesimals → solid core → gas capture','Disk instability','A massive cool disk fragments into giant-planet clumps','Nebular hypothesis','Solar System formed ~4.6 Ga from a collapsing rotating gas–dust cloud','Surface evolution','Differentiation, cratering, flooding, tectonics, erosion, weathering']},
{name:'Planetary Differentiation',place:'study',type:'Theory',icon:'◉',color:'#8e79d6',summary:'Dense materials sink while lighter materials rise in a molten body.',facts:['Iron catastrophe','~4.5 Ga: Fe–Ni sank to form Earth’s core','Silicate differentiation','~4.5–4.4 Ga: mantle and first crust separated','Crustal differentiation','Partial melting forms buoyant continental crust','Atmosphere/hydrosphere','Outgassing followed by water condensation','Core evolution','Inner-core freezing sustains outer-core convection and the geodynamo']},
{name:'Newton’s Laws and Gravity',place:'study',type:'Physics',icon:'ƒ',color:'#59b7a3',summary:'Three laws describe motion; universal gravitation describes attraction between masses.',facts:['First law','Motion remains constant unless a net force acts','Second law','F = ma','Third law','Every action has an equal and opposite reaction','Gravity','F = Gm₁m₂/r²']},
{name:'Kepler’s Laws',place:'study',type:'Physics',icon:'◯',color:'#59b7a3',summary:'Three laws describe planetary orbits.',facts:['First','Ellipses with the Sun at one focus','Second','Equal areas in equal times; faster at perihelion','Third','T² ∝ a³']},
{name:'Lagrange Points',place:'study',type:'Physics',icon:'⌖',color:'#59b7a3',summary:'Five locations where gravity and orbital motion balance.',facts:['L1–L3','Unstable','L4–L5','Stable in suitable systems','Use','Space observatories and Trojan populations']},
{name:'Orbital Resonance',place:'study',type:'Physics',icon:'↻',color:'#59b7a3',summary:'Whole-number period ratios create repeated gravitational interactions.',facts:['Two-body','Neptune–Pluto 3:2; Kirkwood gaps','Laplace resonance','Io–Europa–Ganymede 1:2:4','Effects','Orbital stability, tidal heating, ring structure','1:1 examples','Trojans and Janus–Epimetheus']},
{name:'Roche Limit and Hill Sphere',place:'study',type:'Physics',icon:'◒',color:'#59b7a3',summary:'The Roche limit concerns tidal breakup; the Hill sphere marks local gravitational dominance.',facts:['Roche limit','Inside it, tides can disrupt a gravity-held body','Results','Rings, deformation, comet fragmentation','Hill sphere','Region where a body dominates satellites gravitationally']},
{name:'HR Diagram',place:'study',type:'Astronomy',icon:'⌗',color:'#d164a5',summary:'Plots luminosity against temperature.',facts:['Main sequence','Hot/bright to cool/dim','Giants','Cool and luminous','White dwarfs','Hot and dim']},
{name:'Atmospheres and Magnetism',place:'study',type:'Theory',icon:'◍',color:'#8e79d6',summary:'Escape velocity affects atmospheric retention; magnetic fields can reduce erosion.',facts:['Escape velocity','Proportional to √(M/R)','Dynamo requirements','Rotating, convecting, conductive fluid','Comparison','Earth has a strong dynamo; Mars lost its global field']}
);