window.GUIDE_DATA=[
{name:'Mercury',place:'inside',type:'Planets',icon:'●',color:'#99938b',summary:'Smallest planet; extreme day–night temperatures; almost no atmosphere.',facts:['Diameter','4,879 km','Gravity','0.38 g','Average temperature','167°C','Moons','0','Year','88 days','Axial tilt','0.03°','Synodic period','116 days','Day','59 Earth days','Atmosphere','Exosphere only','Layers','Very large partly liquid iron–nickel core; thin silicate mantle; solid-rock crust']},
{name:'Venus',place:'inside',type:'Planets',icon:'●',color:'#d9a15c',summary:'Hottest planet due to a runaway greenhouse effect; rotates retrograde.',facts:['Diameter','12,104 km','Gravity','0.90 g','Average temperature','465°C','Moons','0','Year','225 days','Axial tilt','177°','Synodic period','584 days','Day','−243 Earth days (retrograde)','Atmosphere','Thick CO₂; sulfuric-acid clouds','Layers','Likely liquid iron–nickel core; silicate mantle; basaltic crust']},
{name:'Earth',place:'inside',type:'Planets',icon:'●',color:'#3e89cf',summary:'Ocean-covered home world and the only planet currently known to support life.',facts:['Diameter','12,742 km','Gravity','1.00 g','Average temperature','15°C','Moons','1','Year','365 days','Axial tilt','23.5°','Synodic period','N/A','Day','24 hours','Atmosphere','Nitrogen and oxygen','Layers','Solid Fe–Ni inner core; liquid Fe–Ni outer core; silicate mantle; continental and oceanic crust']},
{name:'Mars',place:'inside',type:'Planets',icon:'●',color:'#d65a35',summary:'Cold desert with dust storms, extinct volcanoes, and evidence of ancient water.',facts:['Diameter','6,779 km','Gravity','0.38 g','Average temperature','−63°C','Moons','2','Year','687 days','Axial tilt','25°','Synodic period','780 days','Day','24.6 hours','Atmosphere','Thin CO₂','Layers','Iron–nickel–sulfur core; silicate mantle; basaltic crust']},
{name:'Jupiter',place:'inside',type:'Planets',icon:'●',color:'#d69b69',summary:'Largest planet; fast rotation, powerful magnetosphere, and thick H/He atmosphere.',facts:['Diameter','139,820 km','Gravity','2.53 g','Average temperature','−108°C','Moons','95+','Year','12 years','Axial tilt','3.1°','Synodic period','399 days','Day','9.9 hours','Atmosphere','Hydrogen and helium','Layers','Rock/metal/ice core; metallic hydrogen; liquid molecular hydrogen; H/He atmosphere']},
{name:'Saturn',place:'inside',type:'Planets',icon:'◉',color:'#d8bd78',summary:'Gas giant with an extensive icy ring system.',facts:['Diameter','116,460 km','Gravity','1.07 g','Average temperature','−138°C','Moons','140+','Year','29 years','Axial tilt','26.7°','Synodic period','378 days','Day','10.7 hours','Atmosphere','Hydrogen and helium','Layers','Rock/ice core; metallic hydrogen; molecular hydrogen; H/He atmosphere']},
{name:'Uranus',place:'inside',type:'Planets',icon:'●',color:'#79c8d4',summary:'Cyan ice giant that rotates on its side.',facts:['Diameter','50,724 km','Gravity','0.89 g','Average temperature','−195°C','Moons','27','Year','84 years','Axial tilt','98°','Synodic period','370 days','Day','17.2 hours','Atmosphere','H₂, He, and CH₄','Layers','Rock/metal core; water–ammonia–methane icy mantle; H/He/CH₄ atmosphere']},
{name:'Neptune',place:'inside',type:'Planets',icon:'●',color:'#4169cf',summary:'Distant blue ice giant with the Solar System’s strongest winds.',facts:['Diameter','49,244 km','Gravity','1.14 g','Average temperature','−200°C','Moons','14','Year','165 years','Axial tilt','28.3°','Synodic period','367 days','Day','16.1 hours','Atmosphere','H₂, He, and CH₄','Layers','Rock/metal core; water–ammonia–methane icy mantle; H/He/CH₄ atmosphere']},
{name:'Ceres',place:'inside',type:'Dwarf Planets',icon:'◆',color:'#77756f',summary:'Largest object in the asteroid belt.',facts:['Diameter','940 km','Gravity','0.03 g','Temperature','−105°C','Moons','0','Year','4.6 Earth years','Tilt','~4°','Day','9 hours','Atmosphere','Thin water-vapor exosphere','Composition','Rock, hydrated minerals, brines, water ice, salts','Discovered','Giuseppe Piazzi, 1801']},
{name:'Pluto',place:'inside',type:'Dwarf Planets',icon:'●',color:'#b79b84',summary:'Icy dwarf planet with glaciers, mountains, and five moons.',facts:['Diameter','2,377 km','Gravity','0.06 g','Temperature','−232°C','Moons','5','Year','248 years','Tilt','122.5°','Day','6.4 Earth days','Atmosphere','Thin nitrogen–methane','Layers','Rock core; water-ice mantle; N₂/CH₄/CO surface ices','Discovered','Clyde Tombaugh, 1930']},
{name:'Haumea',place:'inside',type:'Dwarf Planets',icon:'◆',color:'#ccd8e8',summary:'Fast-spinning elongated dwarf planet with a ring and two moons.',facts:['Diameter','~1,560 km','Gravity','~0.04 g','Temperature','~−241°C','Moons','2','Year','285 years','Day','3.9 hours','Surface','Crystalline water ice','Discovered','Brown team (2004) and Ortiz et al. (2005)']},
{name:'Makemake',place:'inside',type:'Dwarf Planets',icon:'●',color:'#b88765',summary:'Methane-rich dwarf planet with one known moon.',facts:['Diameter','~1,430 km','Gravity','~0.05 g','Temperature','~−239°C','Moons','1','Year','306 years','Day','22.5 hours','Atmosphere','Very thin or seasonal','Discovered','Brown, Trujillo, and Rabinowitz, 2005']},
{name:'Eris',place:'inside',type:'Dwarf Planets',icon:'●',color:'#d7d9df',summary:'Reflective dwarf planet slightly more massive than Pluto.',facts:['Diameter','2,326 km','Gravity','~0.08 g','Temperature','~−231°C','Moons','1 (Dysnomia)','Year','558 years','Day','25.9 hours','Composition','Methane ice; dense rocky–icy interior','Discovered','Brown, Trujillo, and Rabinowitz, 2005']}
];